### ISSUE TITLE
Change default for `saveUninitialized` to `false`

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-express#17]
https://github.com/digitalbazaar/bedrock-express/blob/master/lib/config.js#L18
See: https://github.com/expressjs/session#saveuninitialized

I suspect these defaults are very old and not correct for most work flows. Most of the time sessions are used for login/authN in bedrock applications. We should therefore default to `false` for saving a session when we don't need to. There's no reason to save a new session to the backing session store for every request that comes from a new client that doesn't transmit a cookie identifying it.

**Comment by mattcollier** [comment]
@dlongley @aljones15 can you report on the status of this?  I was thinking that maybe other express flags that were found that provided a better overall solution?

**Comment by aljones15** [comment]
Have tested this in another project and we could safely set this to false before the mongo upgrade. However, the behavior of `bedrock-session-mongodb` will have to be retested in order to verify that the behaviors stay the same with the latest version of MongoDB. The upgrade to `bedrock-session-mongodb` was a real breaking change i.e. `connect-mongo` had to be upgraded and that might have changed how this flag works with that library.

These were the observed behaviors before the upgrade:

https://gist.github.com/aljones15/3defa74231551e5b9934d79609661ae1

**Comment by dlongley** [comment]
The default should change to `false`.

**Comment by dlongley** [comment]
Addressed by #21.
